algo = input('Digite algo: ')
print(f'o tipo de {algo} é: {type(algo)}')
print(f'{algo} é numérico? {algo.isnumeric()}')
print(f'{algo} é alfa? {algo.isalpha()}')
print(f'{algo} é alfanumérico? {algo.isalnum()}')
print(f'{algo} é decimal? {algo.isdecimal()}')
print(f'{algo} esta em letras minúsculas? {algo.islower()}')
print(f'{algo} está em letras maiúsculas? {algo.isupper()}')